package net.pimenta.alsim.gui;

import net.pimenta.alsim.gui.elements.GraphicComponent;
import net.pimenta.alsim.gui.elements.GraphicNode;
import net.pimenta.alsim.gui.elements.GraphicResistor;
import net.pimenta.alsim.gui.elements.GraphicVSource;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public class NetlistGenerator {

    public static String generate(CircuitEditor editor){
        StringBuilder netlist = new StringBuilder();
        NetResolver resolver = new NetResolver(editor.getNodes(),editor.getWires());

        netlist.append("* Generated by Al.Sim!\n");

        for(GraphicComponent component : editor.getComponents()){
            if(component instanceof GraphicResistor resistor){
                List<GraphicNode> nodes = resistor.getNodes();

                netlist.append("R")
                        .append(resistor.getId())
                        .append(" ")
                        .append(resolver.netOf(nodes.get(0)))
                        .append(" ")
                        .append(resolver.netOf(nodes.get(1)))
                        .append(" ")
                        .append(resistor.getR())
                        .append("\n");
            } else if (component instanceof GraphicVSource vsrc) {
                List<GraphicNode> nodes = vsrc.getNodes();

                netlist.append("V")
                        .append(vsrc.getId())
                        .append(" ")
                        .append(resolver.netOf(nodes.get(0)))
                        .append(" ")
                        .append(resolver.netOf(nodes.get(1)))
                        .append(" ")
                        .append(vsrc.getV())
                        .append("\n");
            }
        }

        netlist.append(".end");
        return netlist.toString();
    }

    public static void generate(CircuitEditor editor, Path path) throws IOException {
        Files.writeString(path,generate(editor));
    }
}
